apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
  labels:
    app: http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-blue
  template:
    metadata:
      labels:
        app: http-blue
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args: ["--text","hello-blue"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080